---
- name: Deploy Application
  hosts: app_server
  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
    
      

    # - name: Stop Tomcat service
    #   systemd:
    #     name: tomcat
    #     state: stopped
    #     enabled: true
    #     daemon_reload: true

    - name: Copy hosts file from local to remote
      copy:
        force: yes
        src  : ../../target/ROOT.war
        dest : "/opt/tomcat/webapps"
        mode : 0700
        owner: tomcat
        group: tomcat  

    #  - name: Start Tomcat service
    #    systemd:
    #      name: tomcat
    #      state: started
    #      enabled: true
    #      daemon_reload: true      
   
